timezone: America/New_York
name: Charles Forman. Stuff I write down.
url: http://www.setpixel.com
markdown: redcarpet
pygments: true
permalink: /:categories/:title
description: Stuff Charles Forman writes.
author: Charles Forman
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/rss.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
exclude: s3_website.yml
